name: Enterprise CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm ci
    - run: cd apps/api && npx prisma validate
    - run: cd apps/api && npx prisma generate
    - run: cd apps/api && npm run build
    - run: cd apps/api && npm test
